#!/usr/local/bin/bash
while getopts "su" opt; do
  case ${opt} in
    s ) # process option s
	echo "config-z370.plist + serials --> config.plist"
	sed      's/XXXXXXXXXXXXXXXXX/C02045609GULNV9A8/g' <config-z370.plist >config.plist
	sed  -i  's/YYYYYYYYYYYY/C02DNUYAJV3Q/g' config.plist
	sed  -i  's/ZZZZZZZZ-ZZZZ-ZZZZ-ZZZZ-ZZZZZZZZZZZZ/F434050B-F6A9-46AD-8A99-2DD81816D85C/g' config.plist 
      ;;
    u ) # process option u
	echo "config.plist - serials --> config-z370.plist"
	sed      's/C02045609GULNV9A8/XXXXXXXXXXXXXXXXX/g' <config.plist >config-z370.plist
	sed  -i  's/C02DNUYAJV3Q/YYYYYYYYYYYY/g' config-z370.plist
	sed  -i  's/F434050B-F6A9-46AD-8A99-2DD81816D85C/ZZZZZZZZ-ZZZZ-ZZZZ-ZZZZ-ZZZZZZZZZZZZ/g' config-z370.plist 
      ;;
    \? ) echo "Usage: cmd [-s] [-u]"
      ;;
  esac
done
